### ISSUE TITLE
Add ratings to posts

### ISSUE THREAD

**Issue by chmac** [GatsbyCentral/gatsbycentral.com#167]
We could use staticman.

* Form with selection of 1-5 stars and submit button
* StaticMan config without any moderation (no PR)
* Can we use a JSON data source where the rating gets appended to an array or something?

**Comment by sarasate** [comment]
@chmac There seems to be a problem with throttling of the GitHub API. `Too many requests in this time frame`. There is an issue in [staticman repo](https://github.com/eduardoboucas/staticman/issues/222).
We probably have to host our own staticman instance.

**Comment by sarasate** [comment]
Done
