### ISSUE TITLE
Staticman is dead

### ISSUE THREAD

**Issue by donaldboulton** [GatsbyCentral/gatsbycentral.com#183]
Access to XMLHttpRequest at 'https://api.staticman.net/v2/entry/GatsbyCentral/gatsbycentral.com/master/ratings' from origin 'https://www.gatsbycentral.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
api.staticman.net/v2/entry/GatsbyCentral/gatsbycentral.com/master/ratings:1 Failed to load resource: net::ERR_FAILED

**Comment by VincentTam** [comment]
You're using the official production API instance, which is unavailable, as reported in eduardoboucas/staticman#306.  However, the Node.JS app works well on self-hosted instances like @staticmanaima, @Bloggerbust-bot, etc.

**Comment by donaldboulton** [comment]
cors issue on my end fixed it, staticman lives
